dataset:
  cls: Example_datasets.ArchiveVOCDataset.ArchiveVOCDataset
  root: sheep-detection
  ann_dir: sheep-detection/annotations
  img_dir: sheep-detection/images
  kwargs: {}
detector:
  cls: searchdet_pipeline.core.detector.SearchDetDetector
  kwargs: {}
metrics:
  - mAP
  - mIoU
  - dice
  - clf_report
run:
  positive_dir: examples/positive
  negative_dir: null
