[project]
name = "ml-segmentation"
version = "0.1.0"
description = ""
authors = [
    {name = "iam@synetra"}
]
readme = "README.md"
requires-python = ">=3.11"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
torch = { version = "^2.4.0", source = "torch-gpu" }
torchvision = "^0.15.0"
transformers = "^4.34.0"
accelerate = "^0.21.0"
opencv-python = "^4.8.0"
opencv-contrib-python = "^4.8.0"
Pillow = "^9.5.0"
numpy = "1.26.4"
scipy = "^1.10.0"
hydra-core = "^1.3.0"
iopath = "^0.1.9"
timm = "^0.6.7"
matplotlib = "^3.7.0"
tqdm = "^4.65.0"
requests = "^2.31.0"
protobuf = "^3.20.0"
sentencepiece = "^0.1.99"
einops = "^0.6.1"
gradio = "^3.35.0"
gradio_client = "^0.2.9"
markdown2 = { version = "^2.4.10", extras = ["all"] }
safetensors = "^0.3.1"
tokenizers = "^0.13.3"
huggingface-hub = "^0.16.4"
av = "^10.0.0"
gdown = "^4.7.1"
kagglehub = "^0.2.0"
seaborn = "^0.12.0"
pandas = "^2.0.0"
scikit-learn = "^1.3.0"
coloredlogs = ""
faiss-cpu
selenium
pycocotools
onnxruntime
onnx
jupyter
segment-anything-hq
torchmetrics = "^1.4.0"
typer = "^0.12.3"
rich = "^13.7.1"

[[tool.poetry.source]]
name = "torch-gpu"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[tool.poetry.scripts]
searchdet-eval = "searchdet_pipeline.eval_classes.typer_cli:main"
searchdet-pipeline = "searchdet_pipeline.cli.main:main"
