dataset:
  cls: evaluate.example_datasets.voc_dataset.VocDataset
  root: ../fruits
  ann_dir: ../fruits/annotations
  img_dir: ../fruits/images
  kwargs: {}
detector:
  cls: flashbone.core.detection.searchdet_detector.SearchDetDetector
  kwargs: {}
metrics:
  - mAP
  - mIoU
  - dice
  - clf_report
run:
  positive_dir: ../examples/positive
  negative_dir: null
  enable_profile: false